### ISSUE TITLE
Try to clarify flow of steps related to Loupe, SpaceRanger, VistoSeg

### ISSUE THREAD

**Issue by lcolladotor** [lmweber/BestPracticesST#20]
Based on Heena's @heenadivecha feedback, we think that it'll be useful to:

* Add a diagram for the Loupe + SpaceRanger + VistoSeg steps
* Add a table for the key files: one column could be the file name, another one the tool that creates it. I guess that a third could be links to parts of the book where we talk about them, almost like a glossary table.

CC @abspangler13 @lmweber

**Comment by lmweber** [comment]
I might also move "Section 7.8: VistoSeg for quantifying cells per spot" (which is currently in the `Space Ranger` chapter) into the `VistoSeg` chapter so that all the `VistoSeg` parts are in one place.

**Comment by lmweber** [comment]
Closing this issue since these chapters have now been moved to the separate [Visium Data Preprocessing](https://lmweber.org/Visium-data-preprocessing/) book.
