### ISSUE TITLE
Small error in Ch. 12.3: PCA

### ISSUE THREAD

**Issue by kinnaryshah** [lmweber/BestPracticesST#38]
I wanted to note an error that I received when trying to run the code chunks in Chapter 12.3. The PCA commands needed to be edited to give the indices of the HVGs instead of the gene_ids. I used this code and it gave me the same results that were produced in the book: 

`top_hvgs_indices <- which(rowData(spe)$gene_id %in% top_hvgs)`
`spe <- runPCA(spe, subset_row = top_hvgs_indices)`

**Comment by lmweber** [comment]
Thank you @kinnaryshah ! I'll check this and will update.

**Comment by lmweber** [comment]
Thanks for submitting this, and apologies for the long delay.

I double-checked and the code in the current version of the book for this seems to be working correctly, so I will close this issue. I think we may have added the gene IDs to the rownames of `rowData` in the data objects, which may have fixed this.
