### ISSUE TITLE
Ch 2: Sequencing Prep Overview Figure is Confusing

### ISSUE THREAD

**Issue by berniejmulvey** [lmweber/BestPracticesST#40]
This is not really on anyone other than 10x themselves, but the image in Chapter 2 showing how UMIs and spatial barcodes are arranged on the chip confusingly says "Partial Read 1" on the opposite end of the oligo from the poly dT. It totally got past me that what they mean "partial read 1 **adapter sequence**" (as opposed to some component of the cDNA) til I did some digging to find additional illustrations.

**Comment by lmweber** [comment]
Thank you!
