### ISSUE TITLE
make SPE object

### ISSUE THREAD

**Issue by prummer** [lmweber/BestPracticesST#45]
I believe it would be helpful if you include somewhere, f.i., in "load data" a code example for building an SPE object from the individual data elements. At the moment all SPE objects are ready-made and loaded from data packages.

**Comment by lmweber** [comment]
Hi @prummer , that is a good idea, thanks. I can definitely add this, e.g. using some toy data / example matrices.

**Comment by lmweber** [comment]
This is now included in a short example in the [Load data](https://lmweber.org/BestPracticesST/chapters/load-data.html) chapter.

The main changes are in commit https://github.com/lmweber/BestPracticesST/commit/db9b7cb79ef01fc6ccb76f6f1154a591c0088138.
